version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: people-org-postgres
    environment:
      POSTGRES_DB: people_and_organizations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # pragma: allowlist secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # LocalStack for AWS services (including Cognito)
  localstack:
    image: localstack/localstack:latest
    container_name: people-org-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=cognito-idp,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack-init:/docker-entrypoint-initaws.d
      - localstack_data:/tmp/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mock OAuth2 server (alternative to LocalStack for simpler testing)
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.10
    container_name: people-org-mock-oauth2
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - JSON_CONFIG_PATH=/config/mock-oauth2-config.json
    volumes:
      - ./docker/mock-oauth2-config.json:/config/mock-oauth2-config.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/default/.well-known/openid-configuration"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for session management (optional)
  redis:
    image: redis:7-alpine
    container_name: people-org-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis_password
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  localstack_data:
  redis_data:

networks:
  default:
    name: people-org-network
