version: '3.8'

# Minimal Docker Compose for running tests
# Use: docker-compose -f docker-compose.test.yml up -d
services:
  postgres-test:
    image: postgres:15-alpine
    container_name: people-org-postgres-test
    environment:
      POSTGRES_DB: people_and_organizations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # pragma: allowlist secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data
